# Generated by Django 3.1.6 on 2021-04-14 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_image', models.ImageField(upload_to='hotel-images')),
                ('hotel_description', models.TextField()),
                ('available_states', models.CharField(choices=[('Telangana', 'Telangana'), ('AP', 'AP'), ('UP', 'UP'), ('MP', 'MP'), ('Kerala', 'Kerala')], max_length=100)),
                ('total_rooms', models.PositiveIntegerField()),
                ('rooms_available', models.PositiveIntegerField()),
                ('hotel_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookedHotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_names', models.ManyToManyField(to='resumeapp.Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
