# Generated by Django 3.1.6 on 2021-04-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Hotels',
        ),
    ]
